### ISSUE TITLE
cannot migrate on first install

### ISSUE THREAD

**Issue by rogerad** [nnjeim/world#18]
hi i just stated to download package and do install 
 iam still on laravel 8
 i got this message

php artisan migrate
Migrating: 2020_07_07_055656_create_countries_table

   ErrorException 

  foreach() argument must be of type array|object, null given

  at vendor/nnjeim/world/src/Database/Migrations/2020_07_07_055656_create_countries_table.php:22
     18▕ 			$table->string('iso2', 2);
     19▕ 			$table->string('name');
     20▕ 			$table->tinyInteger('status')->default(1);
     21▕ 
  ➜  22▕ 			foreach (config('world.migrations.countries.optional_fields') as $field => $value) {
     23▕ 				if ($value['required']) {
     24▕ 					$table->string($field, $value['length'] ?? null);
     25▕ 				}
     26▕ 			}

      +27 vendor frames 
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Process finished with exit code 1.

this might be related to the other issue today - please have a look

**Comment by nnjeim** [comment]
@rogerad Hi thanks for your input. I need to check with you if you have published the config file.
please try php artisan vendor:publish --tag=world --force

**Comment by kodjosama** [comment]
The counties table **sub_region** field was renamed to the **subregion** field. But not the **sub_region** field is present in the countries JSON file. That is the issue

**Comment by nnjeim** [comment]
@rogerad This was fixed in the latest commit. I will publish a release right away.

**Comment by rogerad** [comment]
Hi 

 I did publish the config file

 In the meanwhile I am using another package

 Thank you

**Comment by fnagel** [comment]
@nnjeim Still an issue with v1.1.30

I've just installed your package `composer require nnjeim/world` and installed it like described in the readme `php artisan world:install` but this command failed:

```
Installing nnjeim/world...

   ErrorException 

  foreach() argument must be of type array|object, null given

  at vendor/nnjeim/world/src/Database/Migrations/2020_07_07_055656_create_countries_table.php:22
     18▕                        $table->string('iso2', 2);
     19▕                        $table->string('name');
     20▕                        $table->tinyInteger('status')->default(1);
     21▕
  ➜  22▕                        foreach (config('world.migrations.countries.optional_fields') as $field => $value) {
     23▕                                if ($value['required']) {
     24▕                                        $table->string($field, $value['length'] ?? null);
     25▕                                }
     26▕                        }

      +45 vendor frames 

  46  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

Any idea what is wrong?

**Comment by fnagel** [comment]
Ahh ok, the `php artisan world:install` command did work on the second run.

**Comment by khalidmaquilang** [comment]
`php artisan world:install` return this error `foreach() argument must be of type array|object, null given` fresh installed laravel 11
